/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,
  async redirects() {
    return [
      { source: '/services', destination: '/our-services', permanent: true },
      { source: '/services/', destination: '/our-services/', permanent: true },
      { source: '/home-page', destination: '/', permanent: true },
      { source: '/home-page/', destination: '/', permanent: true },
      { source: '/forex', destination: '/money-exchange', permanent: true },
      { source: '/forex/', destination: '/money-exchange/', permanent: true },
      { source: '/category/uncategorized', destination: '/blog', permanent: true },
      { source: '/category/uncategorized/', destination: '/blog/', permanent: true },
      { source: '/contact', destination: '/locations', permanent: true },
      { source: '/contact/', destination: '/locations/', permanent: true },
      { source: '/contact-us', destination: '/locations', permanent: true },
      { source: '/contact-us/', destination: '/locations/', permanent: true },
      { source: '/about', destination: '/', permanent: true },
      { source: '/about/', destination: '/', permanent: true },
      { source: '/about-us', destination: '/', permanent: true },
      { source: '/about-us/', destination: '/', permanent: true },
      { source: '/check-cashing', destination: '/our-services', permanent: true },
      { source: '/check-cashing/', destination: '/our-services/', permanent: true },
      { source: '/blog/page/2', destination: '/blog', permanent: true },
      { source: '/blog/page/2/', destination: '/blog/', permanent: true },
      { source: '/blog/page/:num', destination: '/blog', permanent: true },
      { source: '/blog/page/:num/', destination: '/blog/', permanent: true },
      { source: '/tag/:slug', destination: '/blog', permanent: true },
      { source: '/tag/:slug/', destination: '/blog/', permanent: true },
      { source: '/author/:slug', destination: '/blog', permanent: true },
      { source: '/author/:slug/', destination: '/blog/', permanent: true },
      { source: '/wp-content/:path*', destination: '/', permanent: true },
      { source: '/wp-admin', destination: '/', permanent: true },
      { source: '/wp-admin/', destination: '/', permanent: true },
      { source: '/wp-login.php', destination: '/', permanent: true },
      { source: '/feed', destination: '/', permanent: true },
      { source: '/feed/', destination: '/', permanent: true },
      { source: '/comments/feed', destination: '/', permanent: true },
      { source: '/comments/feed/', destination: '/', permanent: true },
    ]
  },
  images: {
    domains: ['cdn.sanity.io', 'www.losangelescheckcashing.com', 'i0.wp.com', 'i1.wp.com', 'i2.wp.com'],
  },
}
module.exports = nextConfig
